apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: yagoalexandre00/kubenews:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: kubenews-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app.kubernetes.io/name: kubenews
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      name: "http"
      protocol: "TCP"